#!/usr/bin/env bash
TAG=$(git describe --tags)
VERSION_FILE=pyhbsrecover/__version__.py
cat > ${VERSION_FILE} << EOF
'''NAS RSync Module Version
'''
__git_tag__ = '${TAG}'
__develop__ = len(__git_tag__.split('-')) > 1
__version__ = __git_tag__.split('-')[0] + ('.dev0' if __develop__ else '')
EOF
cat ${VERSION_FILE}
